<a href="https://colab.research.google.com/github/AbdelrahmanElsemary/Python/blob/master/Risk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
#Load the data
from google.colab import files # Use to load data on Google Colab
uploaded = files.upload() # Use to load data on Google Colab
df = pd.read_csv('Risk.csv')
df.head(7)

Saving Risk.csv to Risk (3).csv


Q4       Q5   Q6   Q7           Q8   Q9   RESULT
0  unknown  unknown   no   no          NaN  NaN  0.03642
1  unknown  unknown   no  yes          one   no  0.06176
2  unknown  unknown   no  yes          one  yes  0.06176
3  unknown  unknown   no  yes  greater one   no  0.10460
4  unknown  unknown   no  yes  greater one  yes  0.10460
5  unknown  unknown  one   no          NaN  NaN  0.09469
6  unknown  unknown  one  yes          one   no  0.16020

In [3]:
df.head(100)

Q4       Q5   Q6   Q7           Q8   Q9   RESULT
0   unknown  unknown   no   no          NaN  NaN  0.03642
1   unknown  unknown   no  yes          one   no  0.06176
2   unknown  unknown   no  yes          one  yes  0.06176
3   unknown  unknown   no  yes  greater one   no  0.10460
4   unknown  unknown   no  yes  greater one  yes  0.10460
..      ...      ...  ...  ...          ...  ...      ...
95  7 to 11  unknown  one   no          NaN  NaN  0.11410
96  7 to 11  unknown  one  yes          one   no  0.19300
97  7 to 11  unknown  one  yes          one  yes  0.19300
98  7 to 11  unknown  one  yes  greater one   no  0.32550
99  7 to 11  unknown  one  yes  greater one  yes  0.32550

[100 rows x 7 columns]

In [4]:
df.shape

(360, 7)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 7 columns):
Q4        360 non-null object
Q5        360 non-null object
Q6        360 non-null object
Q7        360 non-null object
Q8        288 non-null object
Q9        288 non-null object
RESULT    360 non-null float64
dtypes: float64(1), object(6)
memory usage: 19.8+ KB


In [6]:
#Count the empty (NaN, NAN, na) values in each column
df.isna().sum()

Q4         0
Q5         0
Q6         0
Q7         0
Q8        72
Q9        72
RESULT     0
dtype: int64

In [7]:
# Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'Q4'. 
df['Q4']= label_encoder.fit_transform(df['Q4']) 
  
df['Q4'].unique() 

array([3, 1, 0, 2])

In [8]:
df.head(150)

Q4        Q5           Q6   Q7           Q8   Q9   RESULT
0     3   unknown           no   no          NaN  NaN  0.03642
1     3   unknown           no  yes          one   no  0.06176
2     3   unknown           no  yes          one  yes  0.06176
3     3   unknown           no  yes  greater one   no  0.10460
4     3   unknown           no  yes  greater one  yes  0.10460
..   ..       ...          ...  ...          ...  ...      ...
145   1  20 to 24  greater one   no          NaN  NaN  0.25110
146   1  20 to 24  greater one  yes          one   no  0.42260
147   1  20 to 24  greater one  yes          one  yes  0.42260
148   1  20 to 24  greater one  yes  greater one   no  0.70680
149   1  20 to 24  greater one  yes  greater one  yes  0.70680

[150 rows x 7 columns]

In [9]:
# Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'Q5'. 
df['Q5']= label_encoder.fit_transform(df['Q5']) 
  
df['Q5'].unique() 

array([5, 4, 2, 0, 1, 3])

In [10]:
# Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'Q6'. 
df['Q6']= label_encoder.fit_transform(df['Q6']) 
  
df['Q6'].unique() 

array([1, 2, 0])

In [11]:
# Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'Q7'. 
df['Q7']= label_encoder.fit_transform(df['Q7']) 
  
df['Q7'].unique() 

array([0, 1])

In [12]:
df.fillna(value=0,axis=None )

Q4  Q5  Q6  Q7           Q8   Q9   RESULT
0     3   5   1   0            0    0  0.03642
1     3   5   1   1          one   no  0.06176
2     3   5   1   1          one  yes  0.06176
3     3   5   1   1  greater one   no  0.10460
4     3   5   1   1  greater one  yes  0.10460
..   ..  ..  ..  ..          ...  ...      ...
355   2   3   0   0            0    0  0.15090
356   2   3   0   1          one   no  0.25490
357   2   3   0   1          one  yes  0.25490
358   2   3   0   1  greater one   no  0.42890
359   2   3   0   1  greater one  yes  0.42890

[360 rows x 7 columns]

In [13]:
#Count the empty (NaN, NAN, na) values in each column
df.isna().sum()

Q4         0
Q5         0
Q6         0
Q7         0
Q8        72
Q9        72
RESULT     0
dtype: int64

In [14]:
df['Q8'].value_counts()

greater one    144
one            144
Name: Q8, dtype: int64

In [15]:
df['Q9'].value_counts()

yes    144
no     144
Name: Q9, dtype: int64

In [0]:
Q8_mapping={"one": 1,"greater one": 2}
df['Q8'] = df['Q8'].map(Q8_mapping)

In [0]:
Q9_mapping={"no": 1,"yes": 2}
df['Q9'] = df['Q9'].map(Q9_mapping)

In [18]:
df.head(360)

Q4  Q5  Q6  Q7   Q8   Q9   RESULT
0     3   5   1   0  NaN  NaN  0.03642
1     3   5   1   1  1.0  1.0  0.06176
2     3   5   1   1  1.0  2.0  0.06176
3     3   5   1   1  2.0  1.0  0.10460
4     3   5   1   1  2.0  2.0  0.10460
..   ..  ..  ..  ..  ...  ...      ...
355   2   3   0   0  NaN  NaN  0.15090
356   2   3   0   1  1.0  1.0  0.25490
357   2   3   0   1  1.0  2.0  0.25490
358   2   3   0   1  2.0  1.0  0.42890
359   2   3   0   1  2.0  2.0  0.42890

[360 rows x 7 columns]

In [0]:
values = {'Q8': 0, 'Q9': 0}
df= df.fillna(value=values)

In [20]:
df.head(360)

Q4  Q5  Q6  Q7   Q8   Q9   RESULT
0     3   5   1   0  0.0  0.0  0.03642
1     3   5   1   1  1.0  1.0  0.06176
2     3   5   1   1  1.0  2.0  0.06176
3     3   5   1   1  2.0  1.0  0.10460
4     3   5   1   1  2.0  2.0  0.10460
..   ..  ..  ..  ..  ...  ...      ...
355   2   3   0   0  0.0  0.0  0.15090
356   2   3   0   1  1.0  1.0  0.25490
357   2   3   0   1  1.0  2.0  0.25490
358   2   3   0   1  2.0  1.0  0.42890
359   2   3   0   1  2.0  2.0  0.42890

[360 rows x 7 columns]

In [0]:
# retrieve numpy array
	#####df = df.values

In [0]:
# split into input (X) and output (y) variables
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [27]:
print(x)

[[3. 5. 1. 0. 0. 0.]
 [3. 5. 1. 1. 1. 1.]
 [3. 5. 1. 1. 1. 2.]
 ...
 [2. 3. 0. 1. 1. 2.]
 [2. 3. 0. 1. 2. 1.]
 [2. 3. 0. 1. 2. 2.]]


In [0]:
# Split the dataset into 80% Training set and 20% Testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [49]:
# Fitting multiple lineaar regression to the training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [54]:
# Predicting the test set results
y_pred = regressor.predict(X_test)
print('Coefficients: \n', regressor.coef_)

Coefficients: 
 [-0.01061726  0.00294503 -0.11403156 -0.06913762  0.14710705  0.00142066]


In [55]:
# The mean squared error
print("Mean squared error: %.2f" % np.mean((regressor.predict(X_test) - y_test) ** 2))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % regressor.score(X_test, y_test))

Mean squared error: 0.01
Variance score: 0.51
